# Generated by Django 5.2.15 on 2026-06-29 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=1)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('poster_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=600)),
                ('abstract_text', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list)),
                ('authors', models.JSONField(default=list)),
                ('affiliations', models.JSONField(default=list)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abstracts', to='congress.session')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_label', models.CharField(max_length=20)),
                ('room', models.CharField(blank=True, max_length=60)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField(null=True)),
                ('title', models.CharField(max_length=600)),
                ('first_author', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(default='talk', max_length=16)),
                ('page', models.IntegerField(null=True)),
                ('abstract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talks', to='congress.abstract')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talks', to='congress.session')),
            ],
            options={
                'ordering': ['date', 'time_start', 'room'],
            },
        ),
    ]
