# Generated by Django 5.2.15 on 2026-06-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairCode',
            fields=[
                ('code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SyncDevice',
            fields=[
                ('token', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('state', models.TextField(default='{}')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
