# Generated by Django 5.2.15 on 2026-06-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0002_paircode_syncdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncdevice',
            name='paired',
            field=models.BooleanField(default=False),
        ),
    ]
