# Generated by Django 5.2.15 on 2026-06-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0003_syncdevice_paired'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncdevice',
            name='devices',
            field=models.JSONField(default=list),
        ),
    ]
