# Generated by Django 5.2.15 on 2026-06-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0004_syncdevice_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncdevice',
            name='revoked',
            field=models.JSONField(default=list),
        ),
    ]
