# Generated by Django 5.2.15 on 2026-06-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0005_syncdevice_revoked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=128)),
                ('talk_id', models.IntegerField(db_index=True)),
                ('filename', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
