# Generated by Django 5.2.15 on 2026-06-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0006_syncphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_enabled', models.BooleanField(default=True)),
                ('photo_sync_enabled', models.BooleanField(default=True)),
                ('photo_max_mb', models.IntegerField(default=8)),
                ('photo_max_per_talk', models.IntegerField(default=50)),
                ('photo_max_per_token_mb', models.IntegerField(default=1024)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
