# Generated by Django 5.2.15 on 2026-06-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0007_serverconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverconfig',
            name='photo_sync_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
